### ISSUE TITLE
Set up domain name and GitHub Actions

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-web2023#7]
https://frankensteinvariorum.github.io should still be available
Let's arrange for frankensteinvariorum.org

Add a GitHub Action
Have a main and dev branch.  
Grab what's in public and move it to the website.

### Link pointing issues on built site
* Try removing `source` from `useEffect()` in Paging.tsx
* Try not to hard-code links in variables 
* Work on creating links into the variorum at root level. 
     * For the interactive reading view: https://frankensteinvariorum.org/edition/ 
     * backup at https://frankensteinvariorum.github.io/edition/

**Comment by raffazizzi** [comment]
This is how I think this could work.

1. Remove basePath and hardcoded `fv-web2023` paths in the code, make sure that everything works from `http://localhost:3000`
2. Create a dev branch where you will continue doing development
3. the master (main) branch should only contain the latest _stable_ code (consider versioning it in `package.json`!)
4. Create a GitHub action that does the following every time the master (main) branch gets updated:
    * build the static site
    * push the results to https://github.com/FrankensteinVariorum/frankensteinvariorum.github.io
   
This will make the website available at frankensteinvariorum.github.io.

Then connect the domain name to the repository: https://github.com/FrankensteinVariorum/frankensteinvariorum.github.io, here are some instructions:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by ebeshero** [comment]
**Plan to launch on Monday August 14**

**Comment by ebeshero** [comment]
Resources:
* https://github.com/withastro/action
