### ISSUE TITLE
Note element issue with interface

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-web2023#9]
In at least two places a `<note>` element is displayed (as a hotspot) in the reading view, but does not respond on click to open the sidepanel. Looking at the standoff spine files, there seems no reason they should not display / be available for display? Passages so far: (The analogous passage in the other editions is also not clickable.) These are both notes by MWS, so they are permanently displayed. 

* https://frankensteinvariorum.org/viewer/Thomas/vol_1_letter_ii/ 
* https://frankensteinvariorum.org/viewer/Thomas/vol_1_chapter_iv/ 

Here is a note that responds properly and on click displays the side panel. This note is from fv-team (wonder if those work differently?) 
https://frankensteinvariorum.org/viewer/1818/vol_2_chapter_iii/

**Comment by Yuying-Jin** [comment]
@ebeshero  I have fixed the problem about note elements. The reason why it did not work is the normalization string is not a valid JSON structure. Python script sometimes wraps the tokens with single quotes sometimes with double ones. Usually, when the tokens includes double quotes, Python is more likely to use single quotes to wrap this token, so I only escape the double quotes between the single quotes; however, after we fixed the longToken in this passage, Python uses double quotes to wrap the token including double quotes, and my old regex did not match and escape them, so normalization could not be converted to the valid JSON structure.

**Comment by Yuying-Jin** [comment]
@ebeshero ![image](https://github.com/FrankensteinVariorum/fv-web2023/assets/62861214/a64961cb-4d7f-49b4-933f-912f7f6404a0)
For [vol_1_letter_ii](https://frankensteinvariorum.org/viewer/Thomas/vol_1_letter_ii/), we need to remove the attributes of the note elements during normalization.
